[programs.localnet]
solana_svelte_counter = "C7SGr2s3HdBuEveTahL9H3CsXQDwxkYEUSRPeJAVeDN5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
wallet = "/Users/silvestrevivo/.config/solana/id.json"
cluster = "localnet"

[scripts]
test = "mocha -t 1000000 tests/"
